import Game.Levels.Magma.L01_RposMagma
import Game.Levels.Magma.L02_OddNotMagma
import Game.Levels.Magma.L03_CompositionAssocitavie
import Game.Levels.Magma.L04_MulTwoMap
import Game.Levels.Magma.L05_RealExpHomo
import Game.Levels.Magma.L06_SubNonAssocitavie
import Game.Levels.Magma.L07_IdentityUnique
import Game.Levels.Magma.L08_IdenityMagmaIso
import Game.Levels.Magma.L09_CRnonIso
