import Game.Metadata

World "BasicGroupTheory"

Level 15

Introduction "
Let H be a subgroup of G.
The set of all left cosets of H is denoted by
G/H:= {g • H | g ∈ G}.

The cardinality of G/H is called the index of H in G.
Note that there is a natural surjection π : G → G/H given by g ↦ gH. Then the fiber π(gH) is gH. We have shown that gH and g'H have a bijection between then. In particular
|G| = |G/H| * |H|. This is called the Lagrange theorem.

In particular, the order of any subgroup is a divisor of the order of the group (when the group is finite).


Recall that a group G is called cyclic if there is an element g ∈ G such that every element in G can be written as g^n for some n ∈ ℤ.

We now prove that if the cardinality of G is a prime number
then it must be a cyclic group.

Pick an element 1 ≠ g ∈ G. The strategy is to prove that the subgroup generated by g is the whole group.
"

open Monoid Group
open scoped Pointwise

variable {G : Type*} [Group G] {g :G} {H : Subgroup G}

open Pointwise
instance : HSMul G (Set G) (Set G):=inferInstance

theorem C2_prod_C2_not_cyclic {C : Type u_1} [Group C] [Fintype C]  (h : Nat.card C = 2) : ¬ IsCyclic (C × C) := by
  intro H
  rw [isCyclic_iff_exists_orderOf_eq_natCard] at H



NewTactic rewrite push_neg
NewTheorem Classical.or_iff_not_imp_left Classical.or_iff_not_imp_right Subgroup.mem_coset_iff_diff_mem_subgroup
